fs: erofs: use backported vmalloc implementation
We already backported new vmalloc on commit 6d772712fa1724c3920ec7ed93cdd2579a3fa07b, so this isn't needed.

Fixes the following errors:
In file included from ../fs/erofs/data.c:13:
In file included from ../fs/erofs/internal.h:27:
../fs/erofs/staging.h:90:21: error: redefinition of 'kvmalloc'
static inline void *kvmalloc(size_t size, gfp_t flags)
                    ^
../include/linux/mm.h:572:21: note: previous definition is here
static inline void *kvmalloc(size_t size, gfp_t flags)
                    ^
In file included from ../fs/erofs/data.c:13:
In file included from ../fs/erofs/internal.h:27:
../fs/erofs/staging.h:109:21: error: redefinition of 'kvzalloc'
static inline void *kvzalloc(size_t size, gfp_t flags)
                    ^
../include/linux/mm.h:580:21: note: previous definition is here
static inline void *kvzalloc(size_t size, gfp_t flags)
                    ^
2 errors generated.